### ISSUE TITLE
chat is stuck (loading) with error: null toast

### ISSUE THREAD

**Issue by datfooldive** [F0x1d/Sense#1]
![Screenshot_20230426-193545_Sense](https://user-images.githubusercontent.com/110718021/234563954-ff325363-a627-432e-983a-305cda691493.png)

i always get this if start new chat
its anoying because i need start new chat again with lost information from last time

**Comment by F0x1d** [comment]
Does it happen always or randomly? I mean, have you ever got any response from ChatGPT in Sense?

**Comment by ghost** [comment]
Can agree, happens to me as well. First time I used it I got the error, so I'm pretty sure always!

**Comment by datfooldive** [comment]
> Does it happen always or randomly? I mean, have you ever got any response from ChatGPT in Sense?

After having a few conversations and it happened

**Comment by F0x1d** [comment]
I've just published v1.0.6, fixed error handling there, check it. Also messages are deleted if got error during request

**Comment by datfooldive** [comment]
> I've just published v1.0.6, fixed error handling there, check it. Also messages are deleted if got error during request

thanks, i will test it and report if got another issue
