### ISSUE TITLE
Token limit message

### ISSUE THREAD

**Issue by b3il0** [F0x1d/Sense#3]
Greetings, 

"This model's maximum context
length is 4097 tokens. However, your..."

![Screenshot_20230704-121210~2](https://github.com/F0x1d/Sense/assets/37301674/776189c3-d658-4b78-86ba-72d04c7bcba0)

This message is cut. However, it suggests that I can do something about the limit–what does it say, or can I do anything?

Thanks.

**Comment by F0x1d** [comment]
it just says about the size of your request. Nothing helpful. I will fix it

**Comment by F0x1d** [comment]
Fixed in 1.0.9
